/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package josuezelaya_lab8;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Ventana_Lab8 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Lab8
     */
    public Ventana_Lab8() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sp_altura = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        sp_poder = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sp_aleta_lamia = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        sp_num_branquias = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        salud_lamias = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        salud_hamadriades = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        salud_silfides = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sp_alas_silfides = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sp_alas_salamandras = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        salud_salamandras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_tipo_hada = new javax.swing.JComboBox<>();
        boton_agregar = new javax.swing.JButton();
        jd_about = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jd_simulacion = new javax.swing.JDialog();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_hada1 = new javax.swing.JComboBox<>();
        cb_hada2 = new javax.swing.JComboBox<>();
        boton_battle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_agregar = new javax.swing.JMenuItem();
        menu_simulacion = new javax.swing.JMenuItem();
        menu_abrir = new javax.swing.JMenuItem();
        menu_guardar = new javax.swing.JMenuItem();
        menu_guardarcomo = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        menu_about = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Hadas");

        jLabel2.setText("Nombre");

        jLabel3.setText("Altura");

        jLabel4.setText("Edad");

        jLabel5.setText("Poder");

        jLabel6.setText("Longitud de Aleta");

        jLabel7.setText("Numero de Branquias");

        jLabel8.setText("Salud");

        salud_lamias.setEditable(false);
        salud_lamias.setText("475.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(sp_num_branquias))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55)
                        .addComponent(sp_aleta_lamia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(113, 113, 113)
                        .addComponent(salud_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sp_aleta_lamia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(sp_num_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(salud_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lamias", jPanel1);

        jLabel9.setText("Salud");

        salud_hamadriades.setEditable(false);
        salud_hamadriades.setText("373.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addComponent(salud_hamadriades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(salud_hamadriades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hamadriades", jPanel2);

        jLabel11.setText("Salud");

        salud_silfides.setEditable(false);
        salud_silfides.setText("563.0");

        jLabel12.setText("Longitud de Alas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(sp_alas_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(64, 64, 64)
                        .addComponent(salud_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(salud_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp_alas_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Silfides", jPanel3);

        jLabel13.setText("Alas");

        jLabel14.setText("Salud");

        salud_salamandras.setEditable(false);
        salud_salamandras.setText("683.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(97, 97, 97)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_alas_salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salud_salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_alas_salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(salud_salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salamandras", jPanel4);

        jLabel10.setText("Seleccione Tipo de Hada:");

        cb_tipo_hada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamias", "Hamadriades", "Silfides", "Salamandras" }));

        boton_agregar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton_agregar.setText("Agregar");
        boton_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sp_altura, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(sp_edad)
                                    .addComponent(sp_poder))
                                .addGap(102, 102, 102)
                                .addComponent(jTabbedPane1))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_tipo_hada, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(boton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_hada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sp_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("El programa consiste en seleccionar hadas \ny realizar una batalla.\nGana la Mejor!!");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jd_aboutLayout = new javax.swing.GroupLayout(jd_about.getContentPane());
        jd_about.getContentPane().setLayout(jd_aboutLayout);
        jd_aboutLayout.setHorizontalGroup(
            jd_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aboutLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_aboutLayout.setVerticalGroup(
            jd_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aboutLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jd_simulacion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jd_simulacionWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_simulacionWindowClosed(evt);
            }
        });

        jLabel15.setText("Hada 1");

        jLabel16.setText("Hada 2");

        jLabel17.setText("Hada 1:");

        jLabel18.setText("Hada 2:");

        boton_battle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_battle.setText("BATTLE!");
        boton_battle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_battleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_simulacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_simulacionLayout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel18)
                                .addGap(34, 34, 34)
                                .addComponent(cb_hada2, 0, 126, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simulacionLayout.createSequentialGroup()
                                .addComponent(cb_hada1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(271, 271, 271)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simulacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_battle)
                .addGap(212, 212, 212))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simulacionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(cb_hada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(boton_battle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");

        menu_agregar.setText("Agregar");
        menu_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_agregarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_agregar);

        menu_simulacion.setText("Simulacion");
        menu_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_simulacionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_simulacion);

        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_abrir);

        menu_guardar.setText("Guardar");
        menu_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_guardar);

        menu_guardarcomo.setText("Guardar Como");
        jMenu1.add(menu_guardarcomo);

        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_salir);

        menu_about.setText("About");
        menu_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aboutActionPerformed(evt);
            }
        });
        jMenu1.add(menu_about);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aboutActionPerformed
        // TODO add your handling code here:
        this.jd_about.setModal(true);
        this.jd_about.pack();
        this.jd_about.setLocationRelativeTo(this);
        this.jd_about.setVisible(true);
    }//GEN-LAST:event_menu_aboutActionPerformed

    private void menu_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_agregarActionPerformed
        // TODO add your handling code here:
        this.jd_agregar.setModal(true);
        this.jd_agregar.pack();
        this.jd_agregar.setLocationRelativeTo(this);
        this.jd_agregar.setVisible(true);
    }//GEN-LAST:event_menu_agregarActionPerformed

    private void boton_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregarMouseClicked
        // TODO add your handling code here:

        if (cb_tipo_hada.getSelectedItem().toString().equals("Lamias")) {
            try {
                nombre = tf_nombre.getText();
                altura = Double.parseDouble(sp_altura.getValue().toString());
                edad = Double.parseDouble(sp_edad.getValue().toString());
                poder = Double.parseDouble(sp_poder.getValue().toString());
                double aleta = Double.parseDouble(sp_aleta_lamia.getValue().toString());
                double branquias = Double.parseDouble(sp_num_branquias.getValue().toString());
                salud = Double.parseDouble(salud_lamias.getText());
                if (aleta <= 5 && branquias <= 8) {
                    lamias.add(new Lamias(aleta, branquias, nombre, altura, edad, salud, poder));

                    JOptionPane.showMessageDialog(this, "Se agrego Lamia exitosamente");
                } else {
                    JOptionPane.showMessageDialog(null, "No mayor a 5 la aleta");
                    JOptionPane.showMessageDialog(null, "No mas de 8 la branquias");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        if (cb_tipo_hada.getSelectedItem().toString().equals("Hamadriades")) {
            try {
                nombre = tf_nombre.getText();
                altura = Double.parseDouble(sp_altura.getValue().toString());
                edad = Double.parseDouble(sp_edad.getValue().toString());
                poder = Double.parseDouble(sp_poder.getValue().toString());
                salud = Double.parseDouble(salud_hamadriades.getText());
                hamadriades.add(new Hamadriades(nombre, altura, edad, salud, poder));
                JOptionPane.showMessageDialog(this, "Agrego Hamadriades");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (cb_tipo_hada.getSelectedItem().toString().equals("Silfides")) {
            try {
                nombre = tf_nombre.getText();
                altura = Double.parseDouble(sp_altura.getValue().toString());
                edad = Double.parseDouble(sp_edad.getValue().toString());
                poder = Double.parseDouble(sp_poder.getValue().toString());
                salud = Double.parseDouble(salud_silfides.getText());
                double alas = Double.parseDouble(sp_alas_silfides.getValue().toString());
                if (alas >= 6) {
                    silfides.add(new Silfides(alas, nombre, altura, edad, salud, poder));
                    JOptionPane.showMessageDialog(this, "Agrego Silfides");
                } else {
                    JOptionPane.showMessageDialog(null, "NO menor a 6 longitud de ala");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (cb_tipo_hada.getSelectedItem().toString().equals("Salamandras")) {
            try {
                nombre = tf_nombre.getText();
                altura = Double.parseDouble(sp_altura.getValue().toString());
                edad = Double.parseDouble(sp_edad.getValue().toString());
                poder = Double.parseDouble(sp_poder.getValue().toString());
                salud = Double.parseDouble(salud_salamandras.getText());
                double alas = Double.parseDouble(sp_alas_salamandras.getValue().toString());
                if (alas >= 16) {
                    salamandras.add(new Salamandras(alas, nombre, altura, edad, salud, poder));
                    JOptionPane.showMessageDialog(this, "Agrego Salamandras");
                } else {
                    JOptionPane.showMessageDialog(null, "No menor de 16 longitud de ala");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_boton_agregarMouseClicked

    private void menu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarActionPerformed
        File Archivo;
        int cont = 0;
        String path = "";
        if (cont > 0) {
            Archivo = new File(path);
            FileOutputStream fw = null;
            ObjectOutputStream bw = null;
            try {
                fw = new FileOutputStream(Archivo);
                bw = new ObjectOutputStream(fw);
                for (Lamias l : lamias) {
                    bw.writeObject(l);
                }
                for (Hamadriades h : hamadriades) {
                    bw.writeObject(h);
                }
                for (Silfides s : silfides) {
                    bw.writeObject(s);
                }
                for (Salamandras ss : salamandras) {
                    bw.writeObject(ss);
                }
                bw.flush();
            } catch (Exception ex) {
            } finally {
                try {
                    bw.close();
                    fw.close();
                } catch (Exception ex) {
                }
            }
        } else {
            JFileChooser fcs = new JFileChooser();
            int aprove = fcs.showSaveDialog(this);
            if (aprove == JFileChooser.APPROVE_OPTION) {
                File fs = fcs.getSelectedFile();
                path = fs.getAbsolutePath();
                FileOutputStream fw = null;
                ObjectOutputStream bw = null;
                try {
                    fw = new FileOutputStream(fs);
                    bw = new ObjectOutputStream(fw);
                    for (Lamias l : lamias) {
                        bw.writeObject(l);
                    }
                    for (Hamadriades h : hamadriades) {
                        bw.writeObject(h);
                    }
                    for (Silfides s : silfides) {
                        bw.writeObject(s);
                    }
                    for (Salamandras ss : salamandras) {
                        bw.writeObject(ss);
                    }
                    bw.flush();
                } catch (Exception ex) {
                } finally {
                    try {
                        bw.close();
                        fw.close();
                    } catch (Exception ex) {
                    }
                }
            }
        }
    }//GEN-LAST:event_menu_guardarActionPerformed

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int op = fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        try {
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            Hadas hada;
            try {
                while ((hada = (Hadas) ois.readObject()) != null) {
                    if (hada instanceof Lamias) {
                        lamias.add((Lamias) hada);
                    } else if (hada instanceof Hamadriades) {
                        hamadriades.add((Hamadriades) hada);
                    } else if (hada instanceof Silfides) {
                        silfides.add((Silfides) hada);
                    } else if (hada instanceof Salamandras) {
                        salamandras.add((Salamandras) hada);
                    }
                }
                Archivo = f;
            } catch (Exception ex) {
            } finally {
                ois.close();
                fis.close();
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void jd_simulacionWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_simulacionWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jd_simulacionWindowClosed

    private void jd_simulacionWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_simulacionWindowActivated
        // TODO add your handling code here:
        if (jd_simulacion.isActive()) {
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel();
            for (Lamias temp : lamias) {
                modelo.addElement(temp);
            }
            for (Hamadriades temp : hamadriades) {
                modelo.addElement(temp);
            }
            for (Silfides temp : silfides) {
                modelo.addElement(temp);
            }
            for (Salamandras temp : salamandras) {
                modelo.addElement(temp);
            }
            cb_hada1.setModel(modelo);
          
        }
         if (jd_simulacion.isActive()) {
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel();
            for (Lamias temp : lamias) {
                modelo.addElement(temp);
            }
            for (Hamadriades temp : hamadriades) {
                modelo.addElement(temp);
            }
            for (Silfides temp : silfides) {
                modelo.addElement(temp);
            }
            for (Salamandras temp : salamandras) {
                modelo.addElement(temp);
            }
           
            cb_hada2.setModel(modelo);
        }
    }//GEN-LAST:event_jd_simulacionWindowActivated

    private void menu_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_simulacionActionPerformed
        // TODO add your handling code here:
        this.jd_simulacion.setModal(true);
        this.jd_simulacion.pack();
        this.jd_simulacion.setLocationRelativeTo(this);
        this.jd_simulacion.setVisible(true);
    }//GEN-LAST:event_menu_simulacionActionPerformed

    private void boton_battleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_battleMouseClicked
        // TODO add your handling code here
        
        p1.run();
        p2.run();
        
    }//GEN-LAST:event_boton_battleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Lab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Lab8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_agregar;
    private javax.swing.JButton boton_battle;
    private javax.swing.JComboBox<String> cb_hada1;
    private javax.swing.JComboBox<String> cb_hada2;
    private javax.swing.JComboBox<String> cb_tipo_hada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jd_about;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JMenuItem menu_about;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JMenuItem menu_agregar;
    private javax.swing.JMenuItem menu_guardar;
    private javax.swing.JMenuItem menu_guardarcomo;
    private javax.swing.JMenuItem menu_salir;
    private javax.swing.JMenuItem menu_simulacion;
    private javax.swing.JTextField salud_hamadriades;
    private javax.swing.JTextField salud_lamias;
    private javax.swing.JTextField salud_salamandras;
    private javax.swing.JTextField salud_silfides;
    private javax.swing.JSpinner sp_alas_salamandras;
    private javax.swing.JSpinner sp_alas_silfides;
    private javax.swing.JSpinner sp_aleta_lamia;
    private javax.swing.JSpinner sp_altura;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_num_branquias;
    private javax.swing.JSpinner sp_poder;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
ArrayList<Lamias> lamias = new ArrayList();
    ArrayList<Hamadriades> hamadriades = new ArrayList();
    ArrayList<Silfides> silfides = new ArrayList();
    ArrayList<Salamandras> salamandras = new ArrayList();
    ArrayList hadas = new ArrayList();
    String nombre;
    double altura, edad, poder, salud;
    File Archivo;
    Hilo p1;
    Hilo p2;
}
